info:
  name: "@project.artifactId@"
  version: "@project.version@"
  description: "@project.description@"
  running-profile: "${spring.profiles.active}"

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  datacenter: Buenos Aires
  environment: Local